spring.application.name=backend
server.port=8080

# Ligação à base de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/DesafioLoginDB
spring.datasource.username=postgres
spring.datasource.password=#Jplindao159

# Configuração do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect